site: Abe Ahn

url: https://abeahn.com
baseurl: 

collections:
  contact:
    output: true
    permalink: /contact
  blog:
    output: true
    permalink: /blog
  finance:
    output: true
    permalink: /finance
  marketing:
    output: true
    permalink: /marketing
  music:
    output: true
    permalink: /music
  projects:
    output: true
    permalink: /projects
  resume:
    output: true
    permalink: /resume
  tech:
    output: true
    permalink: /posts/_tech/:slug


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "contact"
    values:
      layout: "contact"
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"
  -
    scope:
      path: ""
      type: "finance"
    values:
      layout: "finance"
  -
    scope:
      path: ""
      type: "marketing"
    values:
      layout: "marketing"
  -
    scope:
      path: ""
      type: "music"
    values:
      layout: "mmusic"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  -
    scope:
      path: ""
      type: "resume"
    values:
      layout: "resume"
  -
    scope:
      path: ""
      type: "tech"
    values:
      layout: "tech"
      

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/posts/_blog/page-:num/"