site: Made Jekyll Theme

url: 
baseurl: 

collections:
  contact:
    output: true
    permalink: /_contact
  blog:
    output: true
    permalink: /posts/_blog/:slug
  finance:
    output: true
    permalink: /posts/_finance/:slug
  marketing:
    output: true
    permalink: /posts/_marketing/:slug
  music:
    output: true
    permalink: /posts/_music/:slug
  projects:
    output: true
    permalink: /posts/_projects/:slug
  resume:
    output: true
    permalink: /posts/_resume/:slug
  tech:
    output: true
    permalink: /posts/_tech/:slug


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"